Repository chipsalliance/rocket-chip, pull requests merged in 2019-02, with the labels that each got.

#1813 unicode fix
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/tilelink/CLINT.scala
  src/main/scala/devices/tilelink/Plic.scala
Labels: enhancement

#1819 muldiv min div latency fix
  src/main/scala/diplomaticobjectmodel/model/OMMulDiv.scala
Labels: enhancement

#1744 Debug: added halt groups.
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/debug/Periphery.scala
  src/main/scala/devices/debug/dm_registers.scala
Labels: enhancement

#1822 Add ITIM name
  src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
Labels: enhancement

#1823 Added ExportDisableDebug flag to enable optional disable input
  src/main/scala/devices/debug/Periphery.scala
Labels: enhancement

#1824 Global om
  src/main/scala/diplomacy/Resources.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
  src/main/scala/subsystem/BaseSubsystem.scala
Labels: enhancement

#1836 OMISA user fix
  src/main/scala/diplomaticobjectmodel/model/OMISA.scala
Labels: bug

#1844 OMComponents
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala
Labels: bug

#1845 Add external global interrupts
  src/main/scala/diplomacy/Resources.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
Labels: enhancement, merge

#1855 Get last OMComponent
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala
Labels: enhancement

#1856 Add new RegField apply function
  src/main/scala/regmapper/RegField.scala
Labels: enhancement
