Repository chipsalliance/rocket-chip, pull requests merged in 2019-06, with the labels that each got.

#1985 added debugging and refactored the bind function
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
  src/main/scala/rocket/ScratchpadSlavePort.scala
Labels: enhancement

#1987 Rewrote OMECC to fix type issues
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/OMBusMemory.scala
  src/main/scala/diplomaticobjectmodel/model/OMCaches.scala
  src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
  src/main/scala/tilelink/SRAM.scala
Labels: bug, enhancement

#2011 Changed lingering bits of dminner to use dmactive reset
  src/main/scala/devices/debug/Debug.scala
Labels: bug

#2015 Changed DM external triggers from Vec[Bool] to UInt
  src/main/scala/devices/debug/Debug.scala
Labels: enhancement

#2012 PSD: Ensure that PSD is connected to dmactive-derived reset
  src/main/scala/devices/debug/Periphery.scala
Labels: bug

#2014 APB userbits support
  src/main/scala/amba/apb/Bundles.scala
  src/main/scala/amba/apb/Parameters.scala
  src/main/scala/tilelink/Fragmenter.scala
  src/main/scala/tilelink/ToAPB.scala
Labels: enhancement
