Repository chipsalliance/rocket-chip, pull requests merged in 2019-03, with the labels that each got.

#1858 Bump riscv-tools hash to the latest master branch commit
  riscv-tools.hash
Labels: Bumps RISC-V Tools

#1859 adding rangefilter to the getOMMemoryRegions gating expression
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
Labels: enhancement

#1873 Sba 64bit
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/debug/SBA.scala
Labels: bug

#1876 perfmon name fix
  src/main/scala/diplomaticobjectmodel/model/OMPerformanceMonitor.scala
  src/main/scala/tile/RocketTile.scala
Labels: enhancement

#1877 Add customExtension to OMISA
  src/main/scala/diplomaticobjectmodel/model/ISASpecifications.scala
  src/main/scala/diplomaticobjectmodel/model/OMISA.scala
  src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala
Labels: enhancement

#1887 Fix Coverpoint generation in CSR file
  src/main/scala/rocket/CSR.scala
Labels: merge

#1895 Generate different cover points for RO and RW CSR registers
  src/main/scala/rocket/CSR.scala
Labels: merge

#1893 updated the specification hierarchy
  src/main/scala/diplomaticobjectmodel/model/OMSpecification.scala
Labels: enhancement

#1890 Logical tree3
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/debug/Periphery.scala
  src/main/scala/devices/tilelink/CLINT.scala
  src/main/scala/devices/tilelink/Plic.scala
  src/main/scala/diplomacy/Resources.scala
  src/main/scala/diplomaticobjectmodel/ConstructOM.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModel.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/model/OMCoreComplex.scala
  src/main/scala/groundtest/GroundTestSubsystem.scala
  src/main/scala/rocket/Frontend.scala
  src/main/scala/rocket/ICache.scala
  src/main/scala/subsystem/BaseSubsystem.scala
  src/main/scala/subsystem/RocketSubsystem.scala
  src/main/scala/tile/RocketTile.scala
Labels: enhancement
