Repository chipsalliance/rocket-chip, pull requests merged in 2019-10, with the labels that each got.

#2136 Add ecc cover points
  src/main/scala/tilelink/SRAM.scala
Labels: merge, review

#2146 Regfield and reset fixes
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/debug/SBA.scala
Labels: bug

#2125 Events require hits within mask width
  src/main/scala/rocket/Events.scala
Labels: enhancement

#2155 Debug: Make Debug Module optional
  src/main/scala/devices/debug/DMI.scala
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/devices/debug/Periphery.scala
  src/main/scala/devices/debug/SBA.scala
  src/main/scala/rocket/TLB.scala
  src/main/scala/subsystem/Configs.scala
  src/main/scala/subsystem/RocketSubsystem.scala
  src/main/scala/system/TestHarness.scala
Labels: enhancement
