Repository chipsalliance/rocket-chip, pull requests merged in 2019-05, with the labels that each got.

#1935 changing OMDebug based on the new schema
  src/main/scala/devices/debug/Debug.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
Labels: enhancement

#1945 added type field
  src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
Labels: bug

#1957 Fix debug and add omports
  src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
  src/main/scala/diplomaticobjectmodel/model/OMPorts.scala
Labels: enhancement

#1962 handle condition when the Logical Tree equals size 0
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
Labels: bug, enhancement

#1963 fix sram memory regions
  src/main/scala/diplomacy/SRAM.scala
  src/main/scala/diplomaticobjectmodel/model/OMDebug.scala
Labels: bug

#1965 adding object model rocket clock gate
  src/main/scala/diplomaticobjectmodel/logicaltree/RocketLogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/model/OMRocketCore.scala
Labels: enhancement

#1936 adding BusError LTN and OM
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/BusError.scala
  src/main/scala/subsystem/RocketSubsystem.scala
  src/main/scala/tile/BusErrorUnit.scala
  src/main/scala/tile/RocketTile.scala
Labels: enhancement

#1966 fix Vivado parsing errors
  scripts/vlsi_rom_gen
Labels: bug

#1971 Refactoring
  src/main/scala/devices/tilelink/Plic.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/OMCoreComplex.scala
  src/main/scala/diplomaticobjectmodel/model/OMPLIC.scala
  src/main/scala/groundtest/GroundTestSubsystem.scala
  src/main/scala/subsystem/BaseSubsystem.scala
  src/main/scala/subsystem/RocketSubsystem.scala
Labels: enhancement

#1976 refactoring the getOMComponentHelper - removed device
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
Labels: bug, enhancement

#1977 Add RegDesc enumerations to the object model
  src/main/scala/diplomaticobjectmodel/model/OMAddressing.scala
Labels: enhancement

#1975 om bus error
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/OMBusError.scala
  src/main/scala/subsystem/RocketSubsystem.scala
  src/main/scala/tile/BusErrorUnit.scala
  src/main/scala/tile/RocketTile.scala
Labels: enhancement

#1969 Add OMBusMemory
  src/main/scala/amba/ahb/Parameters.scala
  src/main/scala/amba/ahb/SRAM.scala
  src/main/scala/amba/apb/Parameters.scala
  src/main/scala/amba/apb/SRAM.scala
  src/main/scala/amba/axi4/Parameters.scala
  src/main/scala/amba/axi4/SRAM.scala
  src/main/scala/diplomacy/SRAM.scala
  src/main/scala/diplomaticobjectmodel/DiplomaticObjectModelUtils.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTreeNode.scala
  src/main/scala/diplomaticobjectmodel/logicaltree/LogicalTrees.scala
  src/main/scala/diplomaticobjectmodel/model/OMBusMemory.scala
  src/main/scala/diplomaticobjectmodel/model/OMSRAM.scala
  src/main/scala/diplomaticobjectmodel/model/OMTestHarness.scala
  src/main/scala/rocket/DCache.scala
  src/main/scala/rocket/ICache.scala
  src/main/scala/rocket/NBDcache.scala
  src/main/scala/rocket/PTW.scala
  src/main/scala/subsystem/BaseSubsystem.scala
  src/main/scala/tilelink/SRAM.scala
  src/main/scala/util/DescribedSRAM.scala
Labels: enhancement
